### ISSUE TITLE
Find one root, not all possible roots

### ISSUE THREAD

**Issue by takafusui** [tylerjarvis/RootFinding#155]
Dear all,

thank you very much at first for developing an interesting package!

I am solving a system of equations, and if I understood the package correctly, yroots try to find all roots, not a single one, by expanding the size of an array of a variable simultaneously in each iteration.
I admit this is a remarkable feature and perfectly makes sense, but if I am interested in only one root of the system of equations, do you have any tricks to tell yroots to do so?
The size of roots changes every iteration, which causes a broadcast error in my equations.

Thank you in advance.

**Comment by tylerjarvis** [comment]
Our package finds all the real roots in a given (compact) interval.  I am confused by your statement "The size of roots changes every iteration" and I am not sure what you mean by  "broadcast error."  

We don't have a "find only one root" option in our code, but if you only want one root, Newton's method usually works very well.
